INSERT INTO county(county_id,county_name) VALUES ('1','BOMI');
INSERT INTO county(county_id,county_name) VALUES ('2','BONG');
INSERT INTO county(county_id,county_name) VALUES ('3','GBARPOLU');
INSERT INTO county(county_id,county_name) VALUES ('4','GRAND BASSA');
INSERT INTO county(county_id,county_name) VALUES ('5','GRAND CAPE MOUNT');
INSERT INTO county(county_id,county_name) VALUES ('6','GRAND GEDEH');
INSERT INTO county(county_id,county_name) VALUES ('7','GRAND KRU');
INSERT INTO county(county_id,county_name) VALUES ('8','LOFA');
INSERT INTO county(county_id,county_name) VALUES ('9','MARGIBI');
INSERT INTO county(county_id,county_name) VALUES ('10','MARYLAND');
INSERT INTO county(county_id,county_name) VALUES ('11','MONTSERRADO');
INSERT INTO county(county_id,county_name) VALUES ('12','NIMBA');
INSERT INTO county(county_id,county_name) VALUES ('13','RIVER CESS');
INSERT INTO county(county_id,county_name) VALUES ('14','RIVER GEE');
INSERT INTO county(county_id,county_name) VALUES ('15','SINOE');
