INSERT INTO district(district_id,district_name,county_id) VALUES ('1','DOWEIN','1');
INSERT INTO district(district_id,district_name,county_id) VALUES ('2','KLAY','1');
INSERT INTO district(district_id,district_name,county_id) VALUES ('3','SUEHN MECCA','1');
INSERT INTO district(district_id,district_name,county_id) VALUES ('4','SENJEH','1');
INSERT INTO district(district_id,district_name,county_id) VALUES ('5','BOINSEN','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('6','FUAMAH','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('7','JORQUELLEH','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('8','KOKOYAH','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('9','KPAAI','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('10','PANTA','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('11','SALALA','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('12','SANOYEAH','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('13','SUAKOKO','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('14','TUKPAHBLEE','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('15','YEALLEQUELLEH','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('16','ZOTA','2');
INSERT INTO district(district_id,district_name,county_id) VALUES ('17','BELLEH','3');
INSERT INTO district(district_id,district_name,county_id) VALUES ('18','BOPOLU','3');
INSERT INTO district(district_id,district_name,county_id) VALUES ('19','BOKOMU','3');
INSERT INTO district(district_id,district_name,county_id) VALUES ('20','GBARMA','3');
INSERT INTO district(district_id,district_name,county_id) VALUES ('21','GOUNWOLAILA','3');
INSERT INTO district(district_id,district_name,county_id) VALUES ('22','KONGBA','3');
INSERT INTO district(district_id,district_name,county_id) VALUES ('23','COMMONWEALTH','4');
INSERT INTO district(district_id,district_name,county_id) VALUES ('24','DISTRICT #2','4');
INSERT INTO district(district_id,district_name,county_id) VALUES ('25','DISTRICT #1','4');
INSERT INTO district(district_id,district_name,county_id) VALUES ('26','DISTRICT #3','4');
INSERT INTO district(district_id,district_name,county_id) VALUES ('27','DISTRICT #4','4');
INSERT INTO district(district_id,district_name,county_id) VALUES ('28','NEEKREEN','4');
INSERT INTO district(district_id,district_name,county_id) VALUES ('29','OWENSGROVE','4');
INSERT INTO district(district_id,district_name,county_id) VALUES ('30','ST. JOHN RIVER CITY','4');
INSERT INTO district(district_id,district_name,county_id) VALUES ('31','COMMONWEALTH ROBERTSPORT','5');
INSERT INTO district(district_id,district_name,county_id) VALUES ('32','GARWULA','5');
INSERT INTO district(district_id,district_name,county_id) VALUES ('33','GOLA KONNEH','5');
INSERT INTO district(district_id,district_name,county_id) VALUES ('34','PORKPA','5');
INSERT INTO district(district_id,district_name,county_id) VALUES ('35','TEWOR','5');
INSERT INTO district(district_id,district_name,county_id) VALUES ('36','B''HAI','6');
INSERT INTO district(district_id,district_name,county_id) VALUES ('37','CAVALA','6');
INSERT INTO district(district_id,district_name,county_id) VALUES ('38','GBAO','6');
INSERT INTO district(district_id,district_name,county_id) VALUES ('39','GBOE-PLOE','6');
INSERT INTO district(district_id,district_name,county_id) VALUES ('40','GLIO-TWARBO','6');
INSERT INTO district(district_id,district_name,county_id) VALUES ('41','KONOBO','6');
INSERT INTO district(district_id,district_name,county_id) VALUES ('42','PUTU','6');
INSERT INTO district(district_id,district_name,county_id) VALUES ('43','TCHIEN','6');
INSERT INTO district(district_id,district_name,county_id) VALUES ('44','BARCLAYVILLE','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('45','BLEEBO','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('46','BOLLOH','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('47','BUAH','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('48','DORBOR','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('49','DWEH','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('50','FELO-JEKWI','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('51','FENETOE','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('52','FORPOH','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('53','GARRAWAY','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('54','GEE','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('55','GRAND CESS WEDABO','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('56','KPI','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('57','LOWER JLOH','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('58','NROKWIA-WESLDOW','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('59','TRENBO','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('60','UPPER JLOH','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('61','WLOGBA','7');
INSERT INTO district(district_id,district_name,county_id) VALUES ('62','FOYA','8');
INSERT INTO district(district_id,district_name,county_id) VALUES ('63','KOLAHUN','8');
INSERT INTO district(district_id,district_name,county_id) VALUES ('64','QUARDU GBONI','8');
INSERT INTO district(district_id,district_name,county_id) VALUES ('65','SALAYEA','8');
INSERT INTO district(district_id,district_name,county_id) VALUES ('66','VAHUN','8');
INSERT INTO district(district_id,district_name,county_id) VALUES ('67','VOINJAMA','8');
INSERT INTO district(district_id,district_name,county_id) VALUES ('68','ZORZOR','8');
INSERT INTO district(district_id,district_name,county_id) VALUES ('69','FIRESTONE','9');
INSERT INTO district(district_id,district_name,county_id) VALUES ('70','GIBI','9');
INSERT INTO district(district_id,district_name,county_id) VALUES ('71','KAKATA','9');
INSERT INTO district(district_id,district_name,county_id) VALUES ('72','MAMBAH KABA','9');
INSERT INTO district(district_id,district_name,county_id) VALUES ('73','GWELEKPOKEN','10');
INSERT INTO district(district_id,district_name,county_id) VALUES ('74','HARPER','10');
INSERT INTO district(district_id,district_name,county_id) VALUES ('75','KARLUWAY #1','10');
INSERT INTO district(district_id,district_name,county_id) VALUES ('76','KARLUWAY #2','10');
INSERT INTO district(district_id,district_name,county_id) VALUES ('77','NYORKEN','10');
INSERT INTO district(district_id,district_name,county_id) VALUES ('78','PLEEBO/SODOKEN','10');
INSERT INTO district(district_id,district_name,county_id) VALUES ('79','WHOJAH','10');
INSERT INTO district(district_id,district_name,county_id) VALUES ('80','CAREYSBURG','11');
INSERT INTO district(district_id,district_name,county_id) VALUES ('81','GREATER MONROVIA','11');
INSERT INTO district(district_id,district_name,county_id) VALUES ('82','TODEE','11');
INSERT INTO district(district_id,district_name,county_id) VALUES ('83','ST. PAUL RIVER','11');
INSERT INTO district(district_id,district_name,county_id) VALUES ('84','COMMONWEALTH','11');
INSERT INTO district(district_id,district_name,county_id) VALUES ('85','BOE & QUILLA','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('86','BUU-YAO','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('87','DOE','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('88','GARR-BAIN','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('89','GBEHLAY-GEH','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('90','GBI & DORU','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('91','GBOR','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('92','KPARBLEE','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('93','LEEWEHPEA-MAHN','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('94','MEINPEA-MAHN','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('95','SANNIQUELLIE MAHN','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('96','TWAN RIVER','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('97','WEE-GBEHY-MAHN','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('98','YARMEIN','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('99','YARPEA MAHN','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('100','YARWEIN MEHNSONNOH','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('101','ZOE-GBAO','12');
INSERT INTO district(district_id,district_name,county_id) VALUES ('102','BEAWOR','13');
INSERT INTO district(district_id,district_name,county_id) VALUES ('103','CENTRAL RIVERCESS','13');
INSERT INTO district(district_id,district_name,county_id) VALUES ('104','DOEDAIN','13');
INSERT INTO district(district_id,district_name,county_id) VALUES ('105','FEN RIVER','13');
INSERT INTO district(district_id,district_name,county_id) VALUES ('106','JO RIVER','13');
INSERT INTO district(district_id,district_name,county_id) VALUES ('107','NORWEIN','13');
INSERT INTO district(district_id,district_name,county_id) VALUES ('108','SAMGBALOR','13');
INSERT INTO district(district_id,district_name,county_id) VALUES ('109','ZARFLAHN','13');
INSERT INTO district(district_id,district_name,county_id) VALUES ('110','CHEDEPO','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('111','GBEAPO','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('112','GLARO','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('113','KARFORH','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('114','NANEE','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('115','NYENAWLIKEN','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('116','POTUPO','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('117','SARBO','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('118','TUOBO','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('119','NYENEBO','14');
INSERT INTO district(district_id,district_name,county_id) VALUES ('120','BODAE GREENVILLE','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('121','BOKON','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('122','BUTAW','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('123','DUGBE RIVER','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('124','GREENVILLE','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('125','JAEDAE','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('126','JEADEPO','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('127','JUARZON','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('128','KPAYAN','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('129','KULU SHAW BOE','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('130','PLAHN NYARN','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('131','PYNES TOWN','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('132','SANQUIN ONE','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('133','SANQUIN TWO','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('134','SANQUIN THREE','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('135','SEEKON','15');
INSERT INTO district(district_id,district_name,county_id) VALUES ('136','WEDJAH','15');
