INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('142','ASKIRA/UBA','2','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('143','BAMA','3','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('144','BAYO','4','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('145','BIU','5','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('146','CHIBOK','6','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('147','DAMBOA','7','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('148','DIKWA','8','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('149','GUBIO','9','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('150','GUZAMALA','10','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('151','GWOZA','11','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('152','HAWUL','12','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('153','JERE','13','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('154','KAGA','14','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('155','KALA BALGE','15','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('156','KONDUGA','16','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('157','KUKAWA','17','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('158','KWAYA KUSAR','18','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('159','MAFA','19','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('160','MAGUMERI','20','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('161','MAIDUGURI','21','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('162','MARTE','22','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('163','MOBBAR','23','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('164','MONGUNO','24','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('165','NGALA','25','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('166','NGANZAI','26','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('167','SHANI','27','7');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('168','ABI','1','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('169','AKAMKPA','2','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('170','AKPABUYO','3','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('171','BAKASSI','4','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('172','BEKWARRA','5','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('173','BIASE','6','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('174','BOKI','7','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('175','CALABAR MUNICIPALITY','8','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('176','CALABAR SOUTH','9','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('177','ETUNG','10','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('178','IKOM','11','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('179','OBANLIKU','12','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('180','OBUBRA','13','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('181','OBUDU','14','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('182','ODUKPANI','15','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('183','OGOJA','16','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('184','YAKURR','17','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('185','YALA','18','9');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('186','ANIOCHA NORTH','1','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('187','ANIOCHA SOUTH','2','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('188','BOMADI','3','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('189','BURUTU','4','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('190','ETHIOPEEAST','5','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('191','ETHIOPEWEST','6','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('192','IKA NORTH','7','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('193','IKA-SOUTH','8','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('194','ISOKONORTH','9','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('195','ISOKOSOUTH','10','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('196','NDOKWAEAST','11','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('197','NDOKWAWEST','12','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('198','OKPE','13','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('199','OSHIMILINORTH','14','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('200','OSHIMILISOUTH','15','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('201','PATANI','16','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('202','SAPELE','17','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('203','UDU','18','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('204','UGHELLI NORTH','19','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('205','UGHELLISOUTH','20','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('206','UKWUANI','21','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('207','UVWIE','22','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('208','WARRINORTH','23','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('209','WARRISOUTH','24','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('210','WARRISOUTH WEST','25','10');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('211','ABAKALIKI','1','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('212','AFIKPO NORTH','2','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('213','AFIKPO SOUTH','3','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('214','EBONYI','4','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('215','EZZA NORTH','5','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('216','EZZA SOUTH','6','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('217','IKWO','7','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('218','ISHIELU','8','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('219','IVO','9','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('220','IZZI','10','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('221','OHAOZARA','11','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('222','OHAUKWU','12','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('223','ONICHA','13','11');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('224','AKOKO EDO','1','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('225','EGOR','2','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('226','ESAN CENTRAL','3','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('227','ESAN NORTH EAST','4','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('228','ESSAN SOUTH EAST','5','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('229','ESAN WEST','6','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('230','ETSAKO CENTRAL','7','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('231','ETSAKO EAST','8','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('232','ETSAKO WEST','9','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('233','IGUEBEN','10','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('234','IKPOBA/OKHA','11','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('235','OREDO','12','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('236','ORHIONMWON','13','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('237','OVIA NORTH EAST','14','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('238','OVIA SOUTH WEST','15','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('239','OWAN EAST','16','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('240','OWAN WEST','17','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('241','UHUNMWODE','18','12');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('242','ADO EKITI','1','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('243','EFON','2','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('244','EKITI EAST','3','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('245','EKITI WEST','4','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('246','EKITI SOUTH WEST','5','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('247','EMURE','6','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('248','GBOYIN','7','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('249','IDO/OSI','8','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('250','IJERO','9','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('251','IKERE','10','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('252','IKOLE','11','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('253','ILEJEMEJE','12','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('254','IREPODU/IFELO DUN','13','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('255','ISE/ORUN','14','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('256','MOBA','15','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('257','OYE','16','13');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('258','ANINRI','1','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('259','AWGU','2','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('260','ENUGU-EAST','3','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('261','ENUGU-NORTH','4','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('262','ENUGU-SOUTH','5','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('263','EZEAGU','6','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('264','IGBO ETITI','7','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('265','IGBO-EZE NORTH','8','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('266','IGBO-EZE SOUTH','9','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('267','ISI-UZO','10','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('268','NKANU EAST','11','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('269','NKANU WEST','12','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('270','NSUKKA','13','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('271','OJI-RIVER','14','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('272','UDENU','15','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('273','UDI','16','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('274','UZO-UWANI','17','14');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('275','AKKO','1','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('276','BALANGA','2','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('277','BILLIRI','3','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('278','DUKKU','4','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('279','FUNAKAYE','5','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('280','GOMBE','6','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('281','KALTUNGO','7','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('282','KWAMI','8','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('283','NAFADA','9','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('284','SHONGOM','10','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('285','YAMALTU/DEBA','11','16');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('286','ABOH MBAISE','1','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('287','AHAIAZU MBAISE','2','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('288','EHIME MBANO','3','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('289','EZINIHITTE MBAISE','4','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('290','IDEATO NORTH','5','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('291','IDEATO SOUTH','6','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('292','IHITTE/UBOMA (ISINWEKE)','7','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('293','IKEDURU (IHO)','8','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('294','ISIALA MBANO (UMUELEMAI)','9','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('295','ISU (UMUNDUGBA)','10','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('296','MBAITOLU (NWAORIEUBI)','11','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('297','NGOW OKPALA (UMUNEKE)','12','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('298','NJABA (NNENASA)','13','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('299','NWANGELE (ONUNWANGELE ) AMAIGBO','14','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('300','NKWERRE','15','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('301','OBOWO (OTOKO)','16','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('302','OGUTA (OGUTA)','17','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('303','OHAJI/EGBEMA (MMAHU EGBEMA)','18','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('304','OKIGWE (OKIGWE)','19','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('305','ONUIMO','20','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('306','ORLU','21','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('307','ORSU (AWO IDEMILI)','22','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('308','ORU-EAST','23','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('309','ORU-WEST (MGBIDI)','24','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('310','OWERRI-URBAN (OWERRI)','25','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('311','OWERRI NORTH (ORIE URATTA)','26','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('312','OWERRI WEST (UMUGUMA)','27','17');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('313','AUYO','1','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('314','BABURA','2','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('315','BIRNIN-KUDU','3','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('316','BIRNIWA','4','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('317','BUJI','5','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('318','DUTSE','6','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('319','GARKI','7','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('320','GAGARAWA','8','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('321','GUMEL','9','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('322','GURI','10','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('323','GWARAM','11','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('324','GWIWA','12','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('325','HADEJIA','13','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('326','JAHUN','14','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('327','KAFIN-HAUSA','15','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('328','KAUGAMA','16','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('329','KAZAURE','17','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('330','K/KASAMMA','18','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('331','KIYAWA','19','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('332','MAIGATARI','20','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('333','M/MADORI','21','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('334','MIGA','22','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('335','RINGIM','23','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('336','RONI','24','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('337','S/TANKARKAR','25','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('338','TAURA','26','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('339','YANKWASHI','27','18');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('340','BIRNIN GWARI','1','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('341','CHIKUN','2','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('342','GIWA','3','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('343','IGABI','4','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('344','IKARA','5','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('345','JABA','6','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('346','JEMA?A?','7','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('347','KACHIA','8','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('348','KADUNA NORTH','9','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('349','KADUNA SOUTH','10','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('350','KAGARKO','11','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('351','KAJURU','12','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('352','KAURA','13','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('353','KAURU','14','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('354','KUBAU','15','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('355','KUDAN','16','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('356','LERE','17','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('357','MAKARFI','18','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('358','SABON GARI','19','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('359','SANGA','20','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('360','SOBA','21','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('361','ZAGON KATAF','22','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('362','ZARIA','23','20');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('363','AJINGI','1','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('364','ALBASU','2','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('365','BAGWAI','3','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('366','BEBEJI','4','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('367','BICHI','5','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('368','BUNKURE','6','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('369','DALA','7','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('370','DANBATTA','8','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('371','DAWAKIN KUDU','9','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('372','DAWAKIN TOFA','10','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('373','DOGUWA','11','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('374','FAGGE','12','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('375','GABASAWA','13','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('376','GARKO','14','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('377','GARUN MALAM','15','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('378','GAYA','16','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('379','GEZAWA','17','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('380','GWALE','18','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('381','GWARZO','19','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('382','KABO','20','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('383','KANO MUNICIPAL','21','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('384','KARAYE','22','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('385','KIBIYA','23','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('386','KIRU','24','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('387','KUMBOTSO','25','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('388','KUNCHI','26','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('389','KURA','27','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('390','MAKODA','28','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('391','MINJIBIR','29','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('392','MADOBI','30','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('393','NASARAWA','31','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('394','RANO','32','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('395','RIMIN GADO','33','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('396','ROGO','34','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('397','SHANONO','35','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('398','SUMAILA','36','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('399','TAKAI','37','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('400','TARAUNI','38','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('401','TOFA','39','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('402','TUDUN WADA','40','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('403','TSANYAWA','41','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('404','UNGOGO','42','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('405','WARAWA','43','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('406','WUDIL','44','22');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('407','BAKORI','1','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('408','BATAGARAWA','2','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('409','BATSARI','3','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('410','BAURE','4','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('411','BINDAWA','5','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('412','CHARANCHI','6','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('413','DANDUME','7','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('414','DANJA','8','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('415','DAN MUSA','9','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('416','DAURA','10','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('417','DUTSI','11','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('418','DUTSIN-MA','12','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('419','FASKARI','13','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('420','FUNTUA','14','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('421','INGAWA','15','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('422','JIBIA','16','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('423','KAFUR','17','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('424','KAITA','18','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('425','KANKARA','19','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('426','KANKA','20','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('427','KATSINA','21','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('428','KURFI','22','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('429','KUSADA','23','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('430','MAIADUA','24','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('431','MALUMFASHI','25','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('432','MANI','26','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('433','MASHI','27','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('434','MATAZU','28','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('435','MUSAWA','29','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('436','RIMI','30','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('437','SABUWA','31','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('438','SAFANA','32','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('439','SANDAMU','33','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('440','ZANGO','34','23');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('441','ALIERO','1','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('442','AREWA','2','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('443','ARGUNGU','3','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('444','AUGIE','4','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('445','BAGUDO','5','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('446','BIRNIN KEBBI','6','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('447','BUNZA','7','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('448','DANDI','8','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('449','FAKAI','9','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('450','GWANDU','10','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('451','JEGA','11','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('452','KALGO','12','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('453','KOKO/BESSE','13','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('454','MAIYAMA','14','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('455','NGASKI','15','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('456','SAKABA','16','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('457','SHANGA','17','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('458','SURU','18','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('459','WASAGU/DANKO','19','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('460','YAURI','20','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('461','ZURU','21','19');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('462','ADAVI','1','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('463','AJAOKUTA','2','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('464','ANKPA','3','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('465','BASSA','4','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('466','DEKINA','5','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('467','IBAJI','6','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('468','IDAH','7','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('469','IGALA-MELA','8','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('470','IJUMU','9','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('471','KABBA/BUNU','10','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('472','KOGI (KK)','11','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('473','LOKOJA','12','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('474','MOPA-MORO','13','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('475','OFU','14','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('476','OGORI MAGONGO','15','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('477','OKEHI','16','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('478','OKENE','17','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('479','OLAMABORO','18','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('480','OMALA','19','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('481','YAGBA EAST','20','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('482','YAGBA WEST','21','21');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('483','ASA','1','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('484','BARUTEN','2','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('485','EDU','3','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('486','EKITI','4','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('487','IFELODUN','5','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('488','ILORIN EAST','6','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('489','ILORIN SOUTH','7','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('490','ILORIN WEST','8','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('491','IREPODUN','9','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('492','ISIN','10','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('493','KAIAMA','11','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('494','MORO','12','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('495','OFFA','13','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('496','OKE-ERO','14','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('497','OYUN','15','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('498','PATIGI','16','24');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('499','AGEGE','1','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('500','AJEROMI/IFELO DUN','2','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('501','ALIMOSHO','3','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('502','AMUWO-ODOFIN','4','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('503','APAPA','5','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('504','BADAGRY','6','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('505','EPE','7','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('506','ETI-OSA','8','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('507','IBEJU/LEKKI','9','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('508','IFAKO-IJAYE','10','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('509','IKEJA','11','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('510','IKORODU','12','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('511','KOSOFE','13','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('512','LAGOS ISLAND','14','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('513','LAGOS MAINLAND','15','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('514','MUSHIN','16','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('515','OJO','17','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('516','OSHODI-ISOLO','18','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('517','SHOMOLU','19','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('518','SURULERE','20','25');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('519','AKWANGA','1','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('520','AWE','2','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('521','DOMA','3','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('522','KARU','4','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('523','KEANA','5','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('524','KEFFI','6','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('525','KOKONA','7','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('526','LAFIA','8','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('527','NASARAWA','9','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('528','NASARAWA/EGG ON','10','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('529','OBI','11','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('530','TOTO','12','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('531','WAMBA','13','27');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('532','AGAIE','1','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('533','AGWARA','2','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('534','BIDA','3','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('535','BORGU','4','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('536','BOSSO','5','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('537','CHANCHAGA','6','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('538','EDATI','7','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('539','GBAKO','8','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('540','GURARA','9','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('541','KATCHA','10','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('542','KONTAGORA','11','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('543','LAPAI','12','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('544','LAVUN','13','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('545','MAGAMA','14','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('546','MARIGA','15','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('547','MASHEGU','16','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('548','MOKWA','17','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('549','MUNYA','18','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('550','PAIKORO','19','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('551','RAFI','20','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('552','RIJAU','21','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('553','SHIRORO','22','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('554','SULEJA','23','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('555','TAFA','24','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('556','WUSHISHI','25','26');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('557','ABEOKUTA NORTH','1','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('558','ABEOKUTA SOUTH','2','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('559','ADO-ODO-OTA','3','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('560','EGBADO NORTH','4','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('561','EGBADO SOUTH','5','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('562','EWEKORO','6','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('563','IFO','7','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('564','IJEBU EAST','8','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('565','IJEBU NORTH','9','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('566','IJEBU NORTH EAST','10','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('567','IJEBU ODE','11','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('568','IKENNE','12','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('569','IMEKO/AFON','13','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('570','IPOKIA','14','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('571','OBAFEMI/OWOD E','15','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('572','ODEDA','16','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('573','ODOGBOLU','17','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('574','OGUN WATER SIDE','18','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('575','REMO NORTH','19','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('576','SAGAMU','20','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('577','AKOKO NORTH EAST','1','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('578','AKOKO NORTH WEST','2','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('579','AKOKO SOUTH EAST','3','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('580','AKOKO SOUTH WEST','4','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('581','AKURE NORTH','5','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('582','AKURE SOUTH','6','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('583','ESE-ODO','7','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('584','IDANRE','8','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('585','IFEDORE','9','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('586','ILAJE','10','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('587','ILEOLUJI/OKEIGBO','11','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('588','IRELE','12','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('589','ODIGBO','13','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('590','OKITIPUPA','14','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('591','ONDO EAST','15','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('592','ONDO WEST','16','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('593','OSE','17','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('594','OWO','18','28');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('595','ATAKUMOSA EAST','1','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('596','ATAKUNMOSA WEST','2','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('597','AYEDADE','3','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('598','AYEDIRE','4','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('599','BOLUWA-DURO','5','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('600','BORIPE','6','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('601','EDE NORTH','7','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('602','EDE SOUTH','8','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('603','EGBEDORE','9','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('604','EJIGBO','10','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('605','IFE CENTRAL','11','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('606','IFEDAYO','12','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('607','IFE EAST','13','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('608','IFELODUN','14','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('609','IFE NORTH','15','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('610','IFE SOUTH','16','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('611','ILA','17','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('612','ILESA EAST','18','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('613','ILESA WEST','19','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('614','IREPODUN','20','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('615','IREWOLE','21','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('616','ISOKAN','22','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('617','IWO','23','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('618','OBOKUN','24','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('619','ODO-OTIN','25','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('620','OLA-OLUWA','26','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('621','OLORUNDA','27','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('622','ORIADE','28','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('623','OROLU','29','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('624','OSOGBO','30','30');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('625','AFIJIO','1','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('626','AKINYELE','2','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('627','ATIBA','3','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('628','ATISBO','4','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('629','EGBEDA','5','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('630','IBADAN NORTH','6','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('631','IBADAN NORTH EAST','7','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('632','IBADAN NORTH WEST','8','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('633','IBADAN SOUTH EAST','9','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('634','IBADAN SOUTH WEST','10','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('635','IBARAPA CENTRAL','11','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('636','IBARAPA EAST','12','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('637','IBARAPA NORTH','13','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('638','IDO','14','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('639','IREPO','15','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('640','ISEYIN','16','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('641','ITESIWAJU','17','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('642','IWAJOWA','18','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('643','KAJOLA','19','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('644','LAGELU','20','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('645','OGBOMOSO NORTH','21','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('646','OGBOMOSO SOUTH','22','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('647','OGO-OLUWA','23','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('648','OLORUNSOGO','24','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('649','OLUYOLE','25','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('650','ONA-ARA','26','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('651','OORELOPE','27','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('652','ORIIRE','28','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('653','OYO EAST','29','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('654','OYO WEST','30','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('655','SAKI EAST','31','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('656','SAKI WEST','32','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('657','SURULERE','33','31');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('658','BARKIN LADI','1','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('659','BASSA','2','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('660','BOKKOS','3','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('661','JOS EAST','4','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('662','JOS NORTH','5','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('663','JOS SOUTH','6','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('664','KANAM','7','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('665','KANKE','8','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('666','LANG-TANG NORTH','9','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('667','LANG-TANG SOUTH','10','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('668','MANGU','11','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('669','MIKANG','12','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('670','PANKSHIN','13','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('671','QU AN PAN','14','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('672','RIYOM','15','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('673','SHENDAM','16','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('674','WASE','17','32');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('675','ABUA-ODUAL','1','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('676','AHODA EAST','2','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('677','AHOADA WEST','3','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('678','AKUKUTORU','4','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('679','ANDONI','5','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('680','ASARI-TORU','6','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('681','BONNY','7','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('682','DEGEMA','8','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('683','ELEME','9','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('684','EMOHUA','10','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('685','ETCHE','11','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('686','GOKANA','12','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('687','IKWERRE','13','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('688','KHANA','14','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('689','OBIO/AKPOR','15','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('690','OGBA/EGBEMA/NDO NI','16','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('691','OGU/BOLO','17','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('692','OKRIKA','18','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('693','OMUMA','19','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('694','OPOBO/NKORO','20','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('695','OYIGBO','21','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('696','PORT HARCOURT','22','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('697','TAI','23','33');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('698','BENJI','1','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('699','BODINGA','2','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('700','DANGE/SHUNI','3','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('701','GADA','4','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('702','GORONYO','5','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('703','GUDU','6','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('704','GWADABAWA','7','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('705','ILLELA','8','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('706','ISA','9','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('707','KWARE','10','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('708','KEBBE','11','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('709','RABAH','12','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('710','S/BIRNI','13','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('711','SHAGARI','14','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('712','SILAME','15','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('713','SOKOTO NORTH','16','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('714','SOKOTO SOUTH','17','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('715','TAMBUWAL','18','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('716','TANGAZA','19','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('717','TURETA','20','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('718','WAMAKKO','21','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('719','WURNO','22','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('720','YABO','23','34');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('721','ARDO KOLA','1','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('722','BALI','2','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('723','DONGA','3','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('724','GASHAKA','4','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('725','GASSOL','5','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('726','IBI','6','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('727','JALINGO','7','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('728','LAMIDO','8','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('729','KURMI','9','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('730','LAU','10','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('731','SARDAUNA','11','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('732','TAKUM','12','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('733','USSA','13','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('734','WUKARI','14','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('735','YORRO','15','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('736','ZING','16','35');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('737','BADE','1','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('738','BURSUARI','2','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('739','DAMATURU','3','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('740','FIKA','4','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('741','FUNE','5','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('742','GEIDAM','6','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('743','GUJBA','7','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('744','GULANI','8','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('745','JAKUSKO','9','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('746','KARASUWA','10','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('747','MACHINA','11','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('748','NANGERE','12','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('749','NGURU','13','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('750','POTISKUM','14','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('751','TARMUA','15','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('752','YUNUSARI','16','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('753','YUNUFARI','17','36');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('754','ANKA','1','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('755','BAKURA','2','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('756','BIRNIN MAGAJI','3','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('757','BUKKUYUM','4','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('758','BUNGUDU','5','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('759','GUMMI','6','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('760','GUASAU','7','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('761','KAURA NAMODA','8','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('762','MARADUN','9','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('763','MARU','10','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('764','SHINKAFI','11','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('765','TALATA MAFARA','12','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('766','TSAFE','13','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('767','ZURMI','14','37');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('768','ABAJI','1','15');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('769','BWARI','2','15');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('770','GWAGWALADA','3','15');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('771','KUJE','4','15');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('772','KWALI','5','15');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('773','MUNICIPAL','6','15');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('774','YEWA SOUTH','21','29');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('775','JAMAARE','11','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('776','Test lga','','58');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('1','ABIA NORTH','1','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('2','ABA SOUTH','2','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('3','AROCHUKWU','3','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('4','BENDE','4','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('5','IKWUANO','5','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('6','ISIALA NGWA NORTH','6','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('7','ISIALA NGWA SOUTH','7','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('8','ISUIKWUATO','8','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('9','OBINGWA','9','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('10','OHAFIA','10','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('11','OSISIOMA','11','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('12','UGWUNAGBO','12','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('13','UKWA EAST','13','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('14','UKWA WEST','14','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('15','UMUAHIA NORTH','15','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('16','UMUAHIA SOUTH','16','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('17','UMU-NNEOCHI','17','1');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('18','DEMSA','1','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('19','FURORE','2','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('20','GANYE','3','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('21','GEREI','4','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('22','GOMBI','5','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('23','GUYUK','6','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('24','HONG','7','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('25','JADA','8','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('26','LAMURDE','9','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('27','MADAGALI','10','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('28','MAIHA','11','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('29','MAYO-BELWA','12','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('30','MICHIKA','13','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('31','MUBI NORTH','14','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('32','MUBI SOUTH','15','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('33','NUMAN','16','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('34','SHELLENG','17','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('35','SONG','18','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('36','TUNGO','19','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('37','YOLA NORTH','20','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('38','YOLA SOUTH','21','2');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('39','ABAK','1','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('40','EASTERN OBOLO','2','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('41','EKET','3','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('42','ESIT EKET (UQUO)','4','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('43','ESSIEN UDIM','5','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('44','ETIM EKPO','6','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('45','ETINAN','7','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('46','IBENO','8','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('47','IBESIKPO/ASUTAN','9','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('48','IBIONO IBOM','10','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('49','IKA','11','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('50','IKONO','12','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('51','IKOT ABASI','13','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('52','IKOT EKPENE','14','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('53','INI','15','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('54','ITU','16','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('55','MBO','17','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('56','MKPAT ENIN','18','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('57','NSIT ATAI','19','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('58','NSIT IBOM','20','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('59','NSIT UBIUM','21','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('60','OBOT AKARA','22','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('61','KOBO','23','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('62','ONNAA','24','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('63','ORON','25','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('64','ORUKANAM','26','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('65','UDUNG UKO','27','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('66','UKANAFUN','28','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('67','URBAN','29','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('68','URUE OFFONG ORUKO','30','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('69','UYO','31','3');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('70','AGUATA','1','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('71','AYAMELUM','2','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('72','ANAMBRA EAST','3','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('73','ANAMBRA WEST(MBAMILI)','4','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('74','ANAOCHA','5','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('75','AWKA-NORTH','6','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('76','AWKA SOUTH','7','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('77','DUNUKOFIA','8','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('78','EKWUSIGO','9','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('79','IDEMILI NORTH','10','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('80','IDEMILI SOUTH','11','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('81','IHIALA','12','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('82','NJIKOKA','13','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('83','NNEWI NORTH','14','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('84','NNEWI SOUTH','15','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('85','OGBARU','16','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('86','ONITSAHA NORTH','17','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('87','ONITSHA SOUTH','18','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('88','ORUMBA NORTH','19','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('89','ORUMBA SOUTH','20','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('90','OYI','21','4');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('91','ALKALERE','1','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('92','BAUCHI','2','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('93','BOGORO','3','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('94','DAMBAM','4','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('95','DARAZO','5','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('96','DASS','6','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('97','GAMAWA','7','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('98','GANJUWA','8','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('99','GIADE','9','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('100','ITAS/GADAU','10','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('101','KATAGUM','12','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('102','KIRFI','13','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('103','MISAU','14','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('104','NINGI','15','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('105','SHIRA','16','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('106','TAFAWA BALEWA','17','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('107','TORO','18','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('108','WARJI','19','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('109','ZAKI','20','5');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('110','BRASS','1','8');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('111','EKEREMOR','2','8');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('112','KOLOKUMA/OPOKUMA','3','8');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('113','NEMBE','4','8');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('114','OGBIA','5','8');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('115','SAGBAMA','6','8');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('116','SOUTHERN IJAW','7','8');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('117','YENAGOA','8','8');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('118','ADO','1','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('119','AGATU','2','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('120','APA','3','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('121','BURUKU','4','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('122','GBOKO','5','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('123','GUMA','6','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('124','GWER EAST','7','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('125','GWER WEST','8','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('126','KATSINA-ALA','9','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('127','KONSHISHA','10','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('128','KWANDE','11','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('129','LOGO','12','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('130','MAKURDI','13','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('131','OBI','14','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('132','OGBADIBO','15','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('133','OJU','16','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('134','OHIMINI','17','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('135','OKPOKWU','18','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('136','OTUKPO','19','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('137','TARKA','20','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('138','UKUM','21','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('139','USHONGO','22','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('140','VENDEIKYA','23','6');
INSERT INTO lga(lgaid,lganame,lgacode,statecode) VALUES ('141','ABADAM','1','7');
