INSERT INTO states(stateid,statename,statecode) VALUES ('1','ABIA','AB');
INSERT INTO states(stateid,statename,statecode) VALUES ('2','ADAMAWA','AD');
INSERT INTO states(stateid,statename,statecode) VALUES ('3','AKWA IBOM','AI');
INSERT INTO states(stateid,statename,statecode) VALUES ('4','ANAMBRA','AN');
INSERT INTO states(stateid,statename,statecode) VALUES ('5','BAUCHI','BA');
INSERT INTO states(stateid,statename,statecode) VALUES ('6','BENUE','BN');
INSERT INTO states(stateid,statename,statecode) VALUES ('7','BORNO','BO');
INSERT INTO states(stateid,statename,statecode) VALUES ('8','BAYELSA','BY');
INSERT INTO states(stateid,statename,statecode) VALUES ('9','CROSS RIVER','CR');
INSERT INTO states(stateid,statename,statecode) VALUES ('10','DELTA','DT');
INSERT INTO states(stateid,statename,statecode) VALUES ('11','EBONYI','EB');
INSERT INTO states(stateid,statename,statecode) VALUES ('12','EDO','ED');
INSERT INTO states(stateid,statename,statecode) VALUES ('13','EKITI','EK');
INSERT INTO states(stateid,statename,statecode) VALUES ('14','ENUGU','EN');
INSERT INTO states(stateid,statename,statecode) VALUES ('15','FCT','FC');
INSERT INTO states(stateid,statename,statecode) VALUES ('16','GOMBE','GB');
INSERT INTO states(stateid,statename,statecode) VALUES ('17','IMO','IM');
INSERT INTO states(stateid,statename,statecode) VALUES ('18','JIGAWA','JG');
INSERT INTO states(stateid,statename,statecode) VALUES ('19','KEBBI','KB');
INSERT INTO states(stateid,statename,statecode) VALUES ('20','KADUNA','KD');
INSERT INTO states(stateid,statename,statecode) VALUES ('21','KOGI','KG');
INSERT INTO states(stateid,statename,statecode) VALUES ('22','KANO','KN');
INSERT INTO states(stateid,statename,statecode) VALUES ('23','KATSINA','KT');
INSERT INTO states(stateid,statename,statecode) VALUES ('24','KWARA','KW');
INSERT INTO states(stateid,statename,statecode) VALUES ('25','LAGOS','LA');
INSERT INTO states(stateid,statename,statecode) VALUES ('26','NIGER','NG');
INSERT INTO states(stateid,statename,statecode) VALUES ('27','NASSARAWA','NS');
INSERT INTO states(stateid,statename,statecode) VALUES ('28','ONDO','OD');
INSERT INTO states(stateid,statename,statecode) VALUES ('29','OGUN','OG');
INSERT INTO states(stateid,statename,statecode) VALUES ('30','OSUN','OS');
INSERT INTO states(stateid,statename,statecode) VALUES ('31','OYO','OY');
INSERT INTO states(stateid,statename,statecode) VALUES ('32','PLATEAU','PL');
INSERT INTO states(stateid,statename,statecode) VALUES ('33','RIVERS','RV');
INSERT INTO states(stateid,statename,statecode) VALUES ('34','SOKOTO','SO');
INSERT INTO states(stateid,statename,statecode) VALUES ('35','TARABA','TR');
INSERT INTO states(stateid,statename,statecode) VALUES ('36','YOBE','YB');
INSERT INTO states(stateid,statename,statecode) VALUES ('37','ZAMFARA','ZF');
INSERT INTO states(stateid,statename,statecode) VALUES ('38','Federal Government','FG');
